import React from "react"
const Class = () => {
  return (
    <div >
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi rem nostrum error asperiores corrupti corporis doloremque quidem repudiandae, veniam quasi deleniti cum ducimus iusto doloribus repellendus quae cumque architecto obcaecati cupiditate nihil magnam. Excepturi id minus dignissimos, consequuntur veritatis, fugit reprehenderit ullam provident nemo libero ipsam rem eum possimus temporibus iusto culpa doloribus magni, hic inventore? Sunt totam hic vero doloremque odit ullam adipisci ipsam eos, suscipit, nemo obcaecati, modi temporibus molestiae eum assumenda consequuntur quaerat ratione facere labore autem at? Minima nobis in hic ducimus magnam non, expedita id quibusdam perspiciatis? Vero iure quae delectus asperiores vitae ea pariatur id corporis. Aperiam sit ullam voluptates, odio possimus a nisi. Voluptate cumque possimus itaque quas soluta dicta sint laborum fugit obcaecati quidem neque temporibus omnis reiciendis rerum quis doloribus incidunt ipsa, facilis odio nemo tempora! Voluptatem quaerat odio, illo quos repellat adipisci ipsum inventore earum quam. Ipsa veniam, exercitationem impedit explicabo pariatur voluptatum, odit ullam ducimus officiis cumque, facere maxime iure corrupti laboriosam ab assumenda blanditiis tempora inventore aut iusto aliquam voluptates. Quibusdam quasi qui pariatur quos corporis enim iste dolorem ullam! Temporibus quisquam distinctio, ab nostrum nulla eveniet vel tenetur numquam iusto asperiores obcaecati accusantium placeat, voluptas assumenda ducimus, dolores ex qui harum iste. Mollitia similique repellendus reiciendis doloribus cum obcaecati atque quam eum eos suscipit laborum quasi, esse accusamus qui ad facere incidunt voluptates quae quaerat ducimus ex, omnis quod? Exercitationem asperiores ex est unde consequuntur, eligendi vero tempora officia illo, quaerat id quidem pariatur delectus iste! Blanditiis quibusdam, totam voluptates, voluptatibus distinctio reiciendis at dicta dignissimos laudantium impedit consequatur magnam deserunt debitis dolorum tenetur quod recusandae maiores sed. Sunt sapiente eos magni veniam, libero praesentium reprehenderit nam, id, voluptate ullam quis dolores voluptas doloremque. Ipsam, repellendus, animi eos aspernatur facere molestiae velit et minima non voluptate ducimus?</p>
    </div>
  )
}

export default Class