export {default as Home} from "./Home"
export {default as About} from "./About";
export {default as Class} from "./Class";
export {default as Contact} from "./Contact";
export {default as Sublog} from "./Sublog";
export {default as ClassTwo} from "./ClassTwo";
export {default as Error} from "./Error";
export {default as Gallery} from "./Gallery";
export {default as Pricing} from "./Pricing";
export {default as Join} from "./Join";
export {default as SharedLayout} from "./SharedLayout";
export {default as GalleryTwo} from "./GalleryTwo";